name: Start RDP Server on Windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022  # Use the latest stable Windows runner
    steps:

    - name: Download and Setup ngrok
  run: |
    Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    Expand-Archive -Path ngrok.zip -DestinationPath ngrok
    Move-Item -Path ngrok\ngrok.exe -Destination C:\ngrok.exexe C

    - name: Authenticate ngrok
      run: C:\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN

    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start ngrok tunnel for RDP
      run: Start-Process -NoNewWindow -FilePath "C:\ngrok.exe" -ArgumentList "tcp 3389"

    - name: Get public RDP address
      run: |
        Start-Sleep -Seconds 20
        $url = Invoke-RestMethod -Uri http://127.0.0.1:4040/api/tunnels
        $rdp = $url.tunnels[0].public_url
        echo "RDP Address: $rdp" | Out-File -FilePath rdp.txt
        
